use_frameworks!

platform :ios, '9.0'

target 'SEMapFunctionHandler_Example' do
  pod 'SEMapFunctionHandler', :path => '../'

  #高德地图相关SDK（无IDFA版）
  pod 'AMapLocation-NO-IDFA'
  pod 'AMapSearch-NO-IDFA', '6.9.0'
  # pod 'AMap2DMap-NO-IDFA'
  #第三方库
  pod 'MBProgressHUD'
  pod 'Reachability'
  pod 'MJRefresh'
  pod 'SnapKit'
end

