use_frameworks!

platform :ios, '9.0'

target 'SEMapFunctionHandler_Example' do
  pod 'SEMapFunctionHandler', :path => '../'

  target 'SEMapFunctionHandler_Tests' do
    inherit! :search_paths

    
  end
end
